Complete backup/restore scripts and add molecule tests

diff --git a/templates/restore.sh.j2 b/templates/restore.sh.j2
--- a/templates/restore.sh.j2
+++ b/templates/restore.sh.j2
@@ -1,7 +1,130 @@
 #!/usr/bin/env bash
 
-restore_backup=$1
-new_backup=$({{ foreman_backup_bin }})
+# global definitions
+TRUE=0
+FALSE=1
+DEBUG=${FALSE}
+OK=0
+KO=1
 
+function help {
+    echo "$0 OPTIONS <backup directory>"
+    echo
+    echo "OPTIONS:"
+    echo "   --help"
+    echo "   --verbose"
+}
+
+function debug {
+    if [ "${DEBUG}" -eq "${TRUE}" ]; then
+        echo "$@"
+    fi
+}
+
+# parse options (https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash)
+POSITIONAL=()
+while [[ $# -gt 0 ]]
+do
+    key="$1"
+    case $key in
+        --help)
+            help
+            exit ${OK}
+            ;;
+        --debug)
+            DEBUG=${TRUE}
+            shift # past argument
+            ;;
+        *)    # unknown option
+            POSITIONAL+=("$1") # save it in an array for later
+            shift # past argument
+            ;;
+    esac
+done
+set -- "${POSITIONAL[@]}" # restore positional parameters
+
+{% raw %}
+# validate options
+if [ "${#POSITIONAL[@]}" -ne "1" ]; then
+    echo "missing required argument <backup directory>"
+    exit ${KO}
+fi
+{% endraw %}
+
+BKPTARGET=$1
+if [ ! -d ${BKPTARGET} ] ; then
+    echo "backup directory not found"
+    echo "make sure the path exists and is a directory"
+    exit ${KO}
+fi
+
+debug -n "taking rollback backup ... "
+NEW_BKP=$({{ foreman_backup_bin }})
+debug "${NEW_BKP}"
+
+debug -n "stopping postgresql ... "
 systemctl stop postgresql-{{ foreman_postgresql_release }}
+debug "OK"
+
+if [ ! -f "${BKPTARGET}/base.tar.gz" ] ; then
+    echo "File ${BKPTARGET}/base.tar.gz not found. Aborting"
+    echo "make sure the path exists and is a directory"
+    exit ${KO}
+fi
+
+debug -n "clearing postgresql data ... "
+pushd "{{ postgresql_data_dir }}" > /dev/null
+find ./  -delete
+debug "OK"
+
+debug -n "creating restore configuration ... "
+cat <<-EOF > "{{ postgresql_data_dir }}/recovery.conf"
+# -------------------------------
+# PostgreSQL recovery config file
+# -------------------------------
+#
+# Edit this file to provide the parameters that PostgreSQL needs to
+# perform an archive recovery of a database, or to act as a log-streaming
+# replication standby.
+#
+# If "recovery.conf" is present in the PostgreSQL data directory, it is
+# read on postmaster startup.  After successful recovery, it is renamed
+# to "recovery.done" to ensure that we do not accidentally re-enter
+# archive recovery or standby mode.
+#
+#---------------------------------------------------------------------------
+# ARCHIVE RECOVERY PARAMETERS
+#---------------------------------------------------------------------------
+#
+restore_command = ''
+#
+#---------------------------------------------------------------------------
+# RECOVERY TARGET PARAMETERS
+#---------------------------------------------------------------------------
+#
+recovery_target_timeline = 'latest'
+#
+EOF
+chown postgres.postgres "{{ postgresql_data_dir }}/recovery.conf"
+debug "OK"
+
+debug -n "restoring postgresql data ... "
+tar xvzf "${BKPTARGET}/base.tar.gz"
+debug "OK"
+
+if [ ! -f "${BKPTARGET}/pg_wal.tar.gz" ] ; then
+    echo "File ${BKPTARGET}/pg_wal.tar.gz not found. Ignoring"
+else
+    debug -n "restoring wal data ... "
+    pushd pg_wal
+    tar xvzf "${BKPTARGET}/pg_wal.tar.gz"
+    popd
+    debug "OK"
+fi
+
+debug -n "starting postgresql ... "
 systemctl start postgresql-{{ foreman_postgresql_release }}
+debug "OK"
+
+popd > /dev/null
+exit ${OK}
